GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{ 
    "title": "Blog 1",
    "author": "Alphabet", 
    "url": "google.es",
    "likes": 5
}

